name: englishinnovations
favicon: null
layout_spectrum: 0.01349198236130178
typography_spectrum: 0.5900494430679828
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8433130320627242
  lightness: 0.9223660996649414
  saturation: 0.5793710555881262
  rhythmicContrast: 0.9200296262279153
purpose: []
